"""Complete Bubble MCP tool catalog ported from Aria.

This catalog intentionally lists every tool name exposed by the Aria Bubble MCP
server so standalone MCP clients see the full surface area. Tool calls are
dispatched by ``server.tools``; unsupported compiler families can still be
executed by passing an explicit ``write_payload``.
"""

from __future__ import annotations

from typing import Any

ARIA_BUBBLE_TOOL_NAMES: tuple[str, ...] = (
    "refresh_profile_cache",
    "sync_cache",
    "list_events",
    "sync_event_cache",
    "sync_workflow_ref_cache",
    "list_element_ref_maps",
    "resolve_refs",
    "inspect_context",
    "verify_write",
    "sync_element_ref_cache",
    "scan_types",
    "list_data_types",
    "clear_cache",
    "update_text",
    "delete_text",
    "delete_button",
    "delete_checkbox",
    "delete_radio",
    "delete_input",
    "delete_multiline_input",
    "delete_dropdown",
    "delete_datepicker",
    "delete_file_uploader",
    "delete_picture_uploader",
    "delete_searchbox",
    "delete_slider",
    "delete_icon",
    "delete_image",
    "delete_link",
    "delete_shape",
    "delete_alert",
    "delete_video",
    "delete_html",
    "delete_map",
    "update_name",
    "update_placeholder",
    "update_style",
    "update_image",
    "update_icon",
    "update_checkbox",
    "update_datepicker",
    "update_radio",
    "update_slider",
    "update_file_uploader",
    "update_picture_uploader",
    "update_shape",
    "update_video",
    "update_map",
    "update_image_element",
    "update_html",
    "update_text_element",
    "update_icon_element",
    "update_button",
    "update_input",
    "update_multiline_input",
    "update_dropdown",
    "update_searchbox",
    "update_link",
    "update_alert",
    "update_layout",
    "update_style_all",
    "create_page",
    "delete_page",
    "clone_page",
    "create_reusable",
    "update_reusable_type",
    "clone_reusable",
    "create_custom_state",
    "create_group",
    "create_floating_group",
    "create_group_focus",
    "create_table",
    "update_table",
    "update_group",
    "update_group_focus",
    "update_floating_group",
    "update_reusable",
    "create_reusable_instance",
    "update_repeating_group",
    "delete_reusable",
    "delete_repeating_group",
    "delete_table",
    "delete_group",
    "delete_group_focus",
    "delete_floating_group",
    "create_repeating_group",
    "create_text",
    "create_button",
    "create_input",
    "create_multiline_input",
    "create_dropdown",
    "create_searchbox",
    "create_checkbox",
    "create_datepicker",
    "create_radio",
    "create_slider",
    "create_file_uploader",
    "create_picture_uploader",
    "create_shape",
    "create_video",
    "create_image",
    "create_icon",
    "create_html",
    "create_link",
    "create_alert",
    "create_map",
    "build_source_query_json",
    "build_data_source_json",
    "create_popup",
    "update_popup",
    "delete_popup",
    "list_styles",
    "create_style",
    "edit_style",
    "add_style_condition",
    "reorder_style_states",
    "create_workflow",
    "log_the_user_in",
    "log_the_user_out",
    "sign_the_user_up",
    "signup_login_with_a_social_network",
    "send_confirmation_email",
    "make_changes_to_current_user",
    "update_user_credentials",
    "add_action",
    "add_event_action",
    "replace_action",
    "delete_action",
    "cleanup_empty_actions",
    "create_event",
    "create_empty_event",
    "delete_event",
    "set_event_type",
    "set_event_element",
    "map_element_ref",
    "map_workflow_ref",
    "set_event_property",
    "set_comment",
    "add_event_go_to_page",
    "set_event_interval",
    "set_condition_run_when",
    "set_condition_only_when",
    "set_custom_event_name",
    "set_custom_event_parameters",
    "add_custom_event_parameter",
    "set_custom_event_return_types",
    "add_custom_event_return_type",
    "create_from_html",
    "create_styles_from_html",
    "list_colors",
    "update_color",
    "create_color",
    "delete_color",
    "delete_colors",
    "clear_custom_colors",
    "reorder_colors",
    "list_fonts",
    "update_font",
    "create_font",
    "delete_font",
    "create_button_style",
    "rename_style",
    "delete_style",
    "delete_styles",
    "clear_custom_styles",
    "batch",
    "natural",
    "create_data_type",
    "rename_data_type",
    "delete_data_type",
    "delete_data_type_permanently",
    "create_data_field",
    "rename_data_field",
    "delete_data_field",
    "list_privacy_rules",
    "create_privacy_rule",
    "delete_privacy_rule",
    "set_privacy_rule_name",
    "set_privacy_rule_condition",
    "set_privacy_rule_permission",
    "set_privacy_rule_field_visibility",
    "set_privacy_rule_auto_binding",
    "create_option_set",
    "rename_option_set",
    "delete_option_set",
    "create_option_attribute",
    "create_option_value",
    "delete_option_value",
    "list_option_values",
    "rename_option_value",
    "set_option_value_attribute",
    "reorder_option_values",
    "set_app_setting",
    "set_project_setting",
    "list_project_settings",
    "set_data_type_api_exposure",
    "create_api_token",
    "rename_api_token",
    "regenerate_api_token",
    "delete_api_token",
    "list_301_redirects",
    "create_301_redirect",
    "delete_301_redirect",
    "list_app_texts",
    "list_text_matches",
    "convert_text_parts_to_app_text",
    "create_app_text",
    "set_app_text_translation",
    "convert_text_to_app_text",
    "convert_text_path_to_app_text",
    "propagate_app_text",
    "sync_figma_component",
    "sync_component",
    "sync_figma_style",
    "sync_figma_tokens",
    "upload_asset",
)


def legacy_tool_schema(name: str) -> dict[str, Any]:
    return {
        "name": name,
        "description": (
            "Bubble MCP tool ported from Aria. Accepts the original tool arguments. "
            "Pass profile/app_id/execute/compile/context_file for standalone execution, "
            "or pass write_payload to execute an exact Bubble editor payload."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "profile": {"type": "string"},
                "dry_run": {"type": "boolean"},
                "settings_path": {"type": "string"},
                "context": {"type": "string"},
                "parent": {"type": "string"},
                "execute": {"type": "boolean"},
                "confirm": {"type": "boolean"},
                "write_payload": {"type": "object"},
                "payload": {"type": "object"},
            },
            "additionalProperties": True,
        },
    }
