#!/usr/bin/env python3
"""
Canonical element capability registry for CLI/MCP modularization.

Goal:
- Keep one source of truth for which Bubble element types support which
  shared property modules.
- Allow incremental migration from per-tool/per-element hardcoding to
  capability-driven builders.
"""

from __future__ import annotations

from typing import Dict, List, Set

# Shared property modules (canonical, cross-tool names).
CAPABILITY_GROUPS: Dict[str, List[str]] = {
    "global_visibility": [
        "is_visible",
        "collapse_when_hidden",
    ],
    "global_identity": [
        "html_id",
        "unique_id",
        "style",
    ],
    # Layout/sizing
    "size_frame_full": [
        "width",
        "height",
        "min_width",
        "max_width",
        "fixed_width",
        "fit_width",
        "min_height",
        "max_height",
        "fixed_height",
        "fit_height",
    ],
    "size_frame_minmax": [
        "min_width",
        "max_width",
        "fixed_width",
        "min_height",
        "max_height",
        "fixed_height",
    ],
    "container_layout": [
        "layout",
        "container_layout",
        "row_gap",
        "column_gap",
        "overflow_scroll",
    ],
    "aspect_ratio": [
        "use_aspect_ratio",
        "aspect_ratio_width",
        "aspect_ratio_height",
    ],
    "parent_slot_alignment": [
        "horiz_alignment",
        "vert_alignment",
        "nonant_alignment",
    ],
    "children_layout_alignment": [
        "container_horiz_alignment",
        "container_vert_alignment",
    ],
    # Legacy aliases kept for backward compatibility in downstream references.
    "alignment_child": [
        "horiz_alignment",
        "vert_alignment",
        "nonant_alignment",
    ],
    "alignment_container": [
        "container_horiz_alignment",
        "container_vert_alignment",
    ],
    "spacing_margin": [
        "margin_top",
        "margin_bottom",
        "margin_left",
        "margin_right",
    ],
    "spacing_padding": [
        "padding_top",
        "padding_bottom",
        "padding_left",
        "padding_right",
    ],
    # Visual
    "background": [
        "bg_style",
        "bg_color",
        "bg_image",
        "background_color_if_empty_image",
        "crop_responsive",
        "background_size_cover",
        "center_background",
        "repeat_background_vertical",
        "repeat_background_horizontal",
        "gradient_color1",
        "gradient_color2",
        "gradient_mid",
        "gradient_style",
        "gradient_direction",
        "gradient_shape",
        "gradient_size",
        "gradient_xpos",
        "gradient_ypos",
        "gradient_angle",
    ],
    "border_shared": [
        "border_style",
        "border_width",
        "border_color",
        "border_radius",
    ],
    "border_independent": [
        "border_type",
        "all_4_borders",
        "border_style_top",
        "border_style_right",
        "border_style_bottom",
        "border_style_left",
        "border_width_top",
        "border_width_right",
        "border_width_bottom",
        "border_width_left",
        "border_color_top",
        "border_color_right",
        "border_color_bottom",
        "border_color_left",
        "border_roundness_top",
        "border_roundness_right",
        "border_roundness_bottom",
        "border_roundness_left",
    ],
    "shadow": [
        "shadow_style",
        "shadow_h",
        "shadow_v",
        "shadow_blur",
        "shadow_spread",
        "shadow_color",
    ],
    "opacity": ["opacity"],
    "rotation": ["rotation_angle"],
    "interaction_clickable": ["button_disabled"],
    # Content / accessibility / media
    "image_source": ["source"],
    "image_accessibility": ["alt_tag", "title_attribute"],
    "video_source": ["origin", "video_id", "vimeo_control_color"],
    "video_playback": ["autoplay", "loop", "controls"],
    "input_placeholder": ["placeholder"],
    "text_content": ["content"],
    "html_behavior": [
        "display_as_iframe",
        "wait_until_visible",
        "defer_drawing",
    ],
    "text_typography": [
        "no_bbcode",
        "recognize_links",
        "link_color",
        "nofollow",
        "font_family",
        "font_weight",
        "font_alignment",
        "bold",
        "italic",
        "underline",
        "font_color",
        "word_spacing",
        "line_height",
        "letter_spacing",
        "vertical_centering",
        "text_shadow",
        "text_shadow_h",
        "text_shadow_v",
        "text_shadow_blur",
        "text_shadow_color",
    ],
    "text_shadow_controls": [
        "text_shadow",
        "text_shadow_h",
        "text_shadow_v",
        "text_shadow_blur",
        "text_shadow_color",
    ],
    "font_style": [
        "font_size",
        "font_family",
        "font_weight",
        "font_alignment",
        "bold",
        "italic",
        "underline",
        "font_color",
        "word_spacing",
        "line_height",
        "letter_spacing",
        "vertical_centering",
    ],
    "button_icon": [
        "icon_color",
        "icon_size",
        "icon_placement",
        "button_gap",
        "gap",
    ],
    "link_behavior": [
        "show_icon",
        "icon",
        "link_destination",
        "destination_page",
        "url",
        "data_to_send",
        "open_in_new_tab",
        "link_disabled",
        "nofollow",
        "keep_current_page_params",
        "add_parameters",
        "url_parameters",
    ],
    "alert_behavior": [
        "at_to_top",
    ],
    "map_behavior": [
        "data_source",
        "data_source_json",
        "marker_type",
        "marker_data_type",
        "location_field",
        "map_type",
        "map_style",
        "custom_style",
        "style_json",
        "allow_zoom_drag",
        "disable_zoom_scroll",
        "initial_zoom",
        "use_customized_marker_icon",
        "custom_marker_icon",
        "use_customized_marker_icon_for_list",
        "custom_marker_field",
        "custom_selected_icon",
        "custom_selected_icon_image",
        "manual_setting",
        "center",
        "center_json",
        "show_info_window",
        "autoclose",
        "marker_caption_expression",
        "marker_caption_expression_json",
        "show_title_window",
        "auto_close_window",
        "number_of_markers",
        "marker_address",
    ],
    "tooltip_text": ["title_attribute"],
    "tooltip": ["title_attribute"],
    # Data-driven controls
    "data_binding_basic": ["type_of_content", "data_source"],
    "dynamic_choices": [
        "choices",
        "dynamic_type",
        "result_type",
        "query_source_type",
        "result_from_field",
        "constraints_json",
        "sort_field",
        "sort_desc",
        "ignore_empty_constraints",
        "choices_source_json",
        "option_caption_field",
        "default_value",
    ],
    # Element specific
    "floating_positioning": [
        "float_v_relative",
        "float_h_relative",
        "float_zindex",
        "parallax",
    ],
    "is_visible": [
        "is_visible",
    ],
    "group_behavior": [
        "animate_collapse_operation",
        "collapse_animation_style",
    ],
    "repeating_group_behavior": [
        "rows",
        "cell_min_height",
        "cell_min_width",
        "separator_style",
        "separator_width",
        "separator_color",
        "stretch_rows",
        "show_all_items",
        "fixed_columns",
        "columns",
        "scroll_direction",
        "row_cell_gap",
        "column_cell_gap",
        "stretch_columns",
        "masonry",
    ],
    "popup_behavior": [
        "close_by_esc",
        "prevent_user_from_closing_through_esc",
        "grayout_color",
        "greyout_color",
        "grayout_blur",
        "greyout_blur",
    ],
    "group_focus_behavior": [
        "reference",
        "reference_element",
        "offset_top",
        "offset_left",
    ],
    "table_behavior": [
        "header_layout",
        "repeating_layout",
        "cell_layout_header",
        "cell_layout_repeating",
        "header_row_gap",
        "header_column_gap",
        "repeating_row_gap",
        "repeating_column_gap",
        "column_gap_repeating",
        "header_padding_top",
        "header_padding_bottom",
        "header_padding_left",
        "header_padding_right",
        "repeating_padding_top",
        "repeating_padding_bottom",
        "repeating_padding_left",
        "repeating_padding_right",
        "header_style",
        "repeating_style",
        "header_opacity",
        "repeating_opacity",
        "header_bg_style",
        "header_bg_color",
        "header_bg_image",
        "header_gradient_color1",
        "header_gradient_color2",
        "header_gradient_mid",
        "header_gradient_style",
        "header_gradient_direction",
        "header_gradient_shape",
        "header_gradient_size",
        "header_gradient_xpos",
        "header_gradient_ypos",
        "header_gradient_angle",
        "repeating_bg_style",
        "repeating_bg_color",
        "repeating_bg_image",
        "repeating_gradient_color1",
        "repeating_gradient_color2",
        "repeating_gradient_mid",
        "repeating_gradient_style",
        "repeating_gradient_direction",
        "repeating_gradient_shape",
        "repeating_gradient_size",
        "repeating_gradient_xpos",
        "repeating_gradient_ypos",
        "repeating_gradient_angle",
        "header_html_id",
        "repeating_html_id",
        "header_button_disabled",
        "repeating_button_disabled",
        "header_clickable",
        "repeating_clickable",
        "header_sticky",
        "fixed_number_repeating_rows",
        "fixed_number_repeating_axis",
        "row_count",
        "fixed_number_repeating_axis_count",
        "table_direction",
        "stable_pagination",
        "show_partial_last_page",
        "show_partial_list_on_last_page",
        "vertical_separator_style",
        "vertical_separator_width",
        "vertical_separator_color",
        "horizontal_separator_style",
        "horizontal_separator_width",
        "horizontal_separator_color",
    ],
    "input_binding_basic": [
        "auto_binding",
        "bind_field",
        "binding_content_format",
        "content_format",
        "currency_symbol",
        "initial_content",
    ],
    "input_validation": [
        "required",
        "not_submit_on_enter",
        "prevent_submit_on_enter",
        "limit_characters",
        "character_limit",
        "max_characters",
    ],
    "input_state": [
        "disabled",
    ],
    "input_font_style": [
        "font_size",
        "font_family",
        "font_weight",
        "font_alignment",
        "bold",
        "italic",
        "underline",
        "font_color",
        "word_spacing",
        "line_height",
        "letter_spacing",
        "vertical_centering",
        "placeholder_color",
    ],
    "date_time_picker_behavior": [
        "input_type",
        "date_format",
        "custom_format",
        "time_interval",
        "start_week_monday",
        "start_monday",
        "show_month_year_picker",
        "time_format",
        "minimum_date",
        "min_date",
        "maximum_date",
        "max_date",
        "minimum_hour",
        "min_hour",
        "maximum_hour",
        "max_hour",
    ],
    "file_uploader_behavior": [
        "dynamic_link",
        "src",
        "auto_binding",
        "bind_field",
        "private_file",
        "private",
        "attach_to",
        "max_file_size_mb",
        "max_size",
        "max_file_size",
    ],
    "picture_uploader_behavior": [
        "dynamic_link",
        "src",
        "auto_binding",
        "bind_field",
        "private_file",
        "private",
        "attach_to",
        "limit_image_size_before_upload",
        "limit_image_width",
    ],
    "slider_range": [
        "min",
        "max",
        "val",
        "step",
        "range_type",
        "orientation",
        "background_color",
        "handle_color",
        "range_area_color",
    ],
    "radio_layout": ["columns", "use_dynamic_columns", "min_column_width_px", "color"],
}


# Full element map tracked by Bubble element type (%x).
# NOTE: This is intentionally broad and conservative for migration planning.
ELEMENT_CAPABILITIES: Dict[str, List[str]] = {
    "Page": [
        "size_frame_full",
        "children_layout_alignment",
        "spacing_padding",
        "background",
    ],
    "CustomDefinition": [
        "size_frame_minmax",
        "children_layout_alignment",
        "data_binding_basic",
    ],
    "Group": [
        "size_frame_full",
        "container_layout",
        "group_behavior",
        "parent_slot_alignment",
        "children_layout_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "data_binding_basic",
    ],
    "FloatingGroup": [
        "global_identity",
        "size_frame_full",
        "container_layout",
        "children_layout_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "is_visible",
        "floating_positioning",
        "data_binding_basic",
    ],
    "Popup": [
        "size_frame_full",
        "container_layout",
        "popup_behavior",
        "parent_slot_alignment",
        "children_layout_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "data_binding_basic",
    ],
    "RepeatingGroup": [
        "size_frame_full",
        "container_layout",
        "repeating_group_behavior",
        "parent_slot_alignment",
        "children_layout_alignment",
        "spacing_margin",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "data_binding_basic",
    ],
    "Text": [
        "global_visibility",
        "global_identity",
        "size_frame_full",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "text_content",
        "text_typography",
        "tooltip_text",
    ],
    "Button": [
        "global_visibility",
        "global_identity",
        "size_frame_full",
        "parent_slot_alignment",
        "children_layout_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "font_style",
        "button_icon",
        "tooltip_text",
    ],
    "Input": [
        "size_frame_minmax",
        "input_binding_basic",
        "input_validation",
        "input_state",
        "input_font_style",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "input_placeholder",
    ],
    "Dropdown": [
        "size_frame_minmax",
        "input_binding_basic",
        "input_validation",
        "input_state",
        "input_font_style",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "dynamic_choices",
        "input_placeholder",
        "tooltip",
        "tooltip_text",
    ],
    "SearchBox": [
        "size_frame_minmax",
        "input_validation",
        "input_state",
        "input_font_style",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "dynamic_choices",
        "input_placeholder",
        "tooltip",
        "tooltip_text",
    ],
    "MultiLineInput": [
        "size_frame_full",
        "input_binding_basic",
        "input_validation",
        "input_state",
        "input_font_style",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "input_placeholder",
    ],
    "Checkbox": [
        "size_frame_full",
        "input_binding_basic",
        "input_state",
        "font_style",
        "text_shadow_controls",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "input_placeholder",
    ],
    "DateInput": [
        "size_frame_minmax",
        "input_binding_basic",
        "input_validation",
        "input_state",
        "input_font_style",
        "date_time_picker_behavior",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "input_placeholder",
    ],
    "RadioButtons": [
        "size_frame_full",
        "input_binding_basic",
        "input_state",
        "input_placeholder",
        "font_style",
        "text_shadow_controls",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "dynamic_choices",
        "radio_layout",
    ],
    "SliderInput": [
        "size_frame_minmax",
        "input_binding_basic",
        "input_state",
        "parent_slot_alignment",
        "spacing_margin",
        "opacity",
        "rotation",
        "interaction_clickable",
        "slider_range",
    ],
    "FileInput": [
        "size_frame_full",
        "input_validation",
        "input_state",
        "font_style",
        "file_uploader_behavior",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "input_placeholder",
    ],
    "PictureInput": [
        "size_frame_full",
        "input_validation",
        "input_state",
        "font_style",
        "picture_uploader_behavior",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "input_placeholder",
    ],
    "Shape": [
        "global_visibility",
        "global_identity",
        "size_frame_minmax",
        "aspect_ratio",
        "parent_slot_alignment",
        "spacing_margin",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
    ],
    "Video": [
        "global_visibility",
        "global_identity",
        "size_frame_minmax",
        "aspect_ratio",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "video_source",
        "video_playback",
    ],
    "Image": [
        "global_visibility",
        "global_identity",
        "size_frame_full",
        "aspect_ratio",
        "parent_slot_alignment",
        "spacing_margin",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "image_source",
        "image_accessibility",
        "tooltip_text",
    ],
    "Icon": [
        "global_visibility",
        "global_identity",
        "size_frame_minmax",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "interaction_clickable",
        "text_shadow_controls",
        "tooltip_text",
    ],
    "HTML": [
        "global_visibility",
        "global_identity",
        "size_frame_full",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "rotation",
        "text_content",
        "html_behavior",
    ],
    # Visible element types queued for MCP mapping parity.
    "Link": [
        "global_visibility",
        "global_identity",
        "size_frame_full",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "interaction_clickable",
        "text_content",
        "font_style",
        "text_shadow_controls",
        "link_behavior",
        "tooltip_text",
    ],
    "Alert": [
        "global_identity",
        "size_frame_full",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "text_content",
        "font_style",
        "text_shadow_controls",
        "alert_behavior",
    ],
    "Map": [
        "global_visibility",
        "global_identity",
        "size_frame_minmax",
        "aspect_ratio",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "map_behavior",
    ],
    "GroupFocus": [
        "global_identity",
        "size_frame_full",
        "container_layout",
        "group_focus_behavior",
        "children_layout_alignment",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "data_binding_basic",
    ],
    "Table": [
        "size_frame_full",
        "table_behavior",
        "parent_slot_alignment",
        "spacing_margin",
        "spacing_padding",
        "background",
        "border_shared",
        "border_independent",
        "shadow",
        "opacity",
        "data_binding_basic",
    ],
}


TOOL_ELEMENT_MAP: Dict[str, str] = {
    "create_group": "Group",
    "create_floating_group": "FloatingGroup",
    "create_group_focus": "GroupFocus",
    "create_table": "Table",
    "create_repeating_group": "RepeatingGroup",
    "create_popup": "Popup",
    "create_reusable": "CustomDefinition",
    "create_text": "Text",
    "create_button": "Button",
    "create_input": "Input",
    "create_multiline_input": "MultiLineInput",
    "create_dropdown": "Dropdown",
    "create_searchbox": "SearchBox",
    "create_checkbox": "Checkbox",
    "create_datepicker": "DateInput",
    "create_radio": "RadioButtons",
    "create_slider": "SliderInput",
    "create_file_uploader": "FileInput",
    "create_picture_uploader": "PictureInput",
    "create_shape": "Shape",
    "create_video": "Video",
    "create_image": "Image",
    "create_icon": "Icon",
    "create_html": "HTML",
    # Planned visible element tools (capability stubs for upcoming MCP work).
    "create_link": "Link",
    "create_alert": "Alert",
    "create_map": "Map",
    # Update tools (MCP + CLI parity)
    "update_group": "Group",
    "update_floating_group": "FloatingGroup",
    "update_table": "Table",
    "update_checkbox": "Checkbox",
    "update_datepicker": "DateInput",
    "update_radio": "RadioButtons",
    "update_slider": "SliderInput",
    "update_file_uploader": "FileInput",
    "update_picture_uploader": "PictureInput",
    "update_text": "Text",
    "update_text_element": "Text",
    "update_button": "Button",
    "update_input": "Input",
    "update_multiline_input": "MultiLineInput",
    "update_dropdown": "Dropdown",
    "update_searchbox": "SearchBox",
    "update_icon": "Icon",
    "update_icon_element": "Icon",
    "update_link": "Link",
    "update_image": "Image",
    "update_image_element": "Image",
    "update_shape": "Shape",
    "update_video": "Video",
    "update_html": "HTML",
    "update_alert": "Alert",
    "update_map": "Map",
    # CLI hyphen variants (used by batch command payloads)
    "create-group-focus": "GroupFocus",
    "create-floating-group": "FloatingGroup",
    "create-table": "Table",
    "create-multiline-input": "MultiLineInput",
    "create-searchbox": "SearchBox",
    "update-group": "Group",
    "update-table": "Table",
    "update-checkbox": "Checkbox",
    "update-datepicker": "DateInput",
    "update-radio": "RadioButtons",
    "update-slider": "SliderInput",
    "update-file-uploader": "FileInput",
    "update-picture-uploader": "PictureInput",
    "update-text": "Text",
    "update-text-element": "Text",
    "update-button": "Button",
    "update-input": "Input",
    "update-multiline-input": "MultiLineInput",
    "update-dropdown": "Dropdown",
    "update-searchbox": "SearchBox",
    "update-icon": "Icon",
    "update-icon-element": "Icon",
    "update-link": "Link",
    "update-image": "Image",
    "update-image-element": "Image",
    "update-shape": "Shape",
    "update-video": "Video",
    "update-html": "HTML",
    "update-alert": "Alert",
    "update-map": "Map",
    "update-floating-group": "FloatingGroup",
    "delete_input": "Input",
    "delete_multiline_input": "MultiLineInput",
    "delete_dropdown": "Dropdown",
    "delete_searchbox": "SearchBox",
    "delete-input": "Input",
    "delete-multiline-input": "MultiLineInput",
    "delete-dropdown": "Dropdown",
    "delete-searchbox": "SearchBox",
}

# Optional per-element overrides to explicitly disable/enable properties
# even when they are part of a broader capability group.
ELEMENT_PROPERTY_OVERRIDES: Dict[str, Dict[str, List[str]]] = {
    "FileInput": {
        "disable": [
            "use_aspect_ratio",
            "aspect_ratio_width",
            "aspect_ratio_height",
            "row_gap",
            "column_gap",
        ]
    },
    "Shape": {
        "disable": ["row_gap", "column_gap"]
    },
    "Video": {
        "disable": ["row_gap", "column_gap"]
    },
    "Image": {
        "disable": ["row_gap", "column_gap"]
    },
    "Icon": {
        "disable": ["row_gap", "column_gap"],
        "enable": ["spin_icon", "icon_color"],
    },
    "Map": {
        "disable": ["row_gap", "column_gap"]
    },
}

GLOBAL_VISIBILITY_EXCEPTIONS: Set[str] = {"Alert"}


def capability_properties(group_name: str) -> List[str]:
    return list(CAPABILITY_GROUPS.get(group_name, []))


def element_capability_groups(element_type: str) -> List[str]:
    groups = list(ELEMENT_CAPABILITIES.get(element_type, []))
    if (
        element_type in ELEMENT_CAPABILITIES
        and element_type not in GLOBAL_VISIBILITY_EXCEPTIONS
        and "global_visibility" not in groups
    ):
        groups.append("global_visibility")
    if element_type in ELEMENT_CAPABILITIES and "global_identity" not in groups:
        groups.append("global_identity")
    return groups


def element_supported_properties(element_type: str) -> List[str]:
    props: List[str] = []
    seen: Set[str] = set()
    groups = list(ELEMENT_CAPABILITIES.get(element_type, []))
    if (
        element_type in ELEMENT_CAPABILITIES
        and element_type not in GLOBAL_VISIBILITY_EXCEPTIONS
        and "global_visibility" not in groups
    ):
        groups.append("global_visibility")
    if element_type in ELEMENT_CAPABILITIES and "global_identity" not in groups:
        groups.append("global_identity")
    for group in groups:
        for prop in CAPABILITY_GROUPS.get(group, []):
            if prop not in seen:
                seen.add(prop)
                props.append(prop)
    overrides = ELEMENT_PROPERTY_OVERRIDES.get(element_type, {})
    disabled = set(overrides.get("disable", []))
    enabled = [p for p in overrides.get("enable", []) if p]
    if disabled:
        props = [p for p in props if p not in disabled]
    for prop in enabled:
        if prop not in props:
            props.append(prop)
    return props


def element_disabled_properties(element_type: str) -> List[str]:
    return list((ELEMENT_PROPERTY_OVERRIDES.get(element_type, {}) or {}).get("disable", []))
